apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-cmp-helm-dependency
  namespace: argocd-system
spec:
  project: default
  source:
    path: ./helm-dependency/
    repoURL: https://git.homecredit.net/country/vn/k8s/deploy/environments/vn/nprod-green/argocd-example-apps.git
  destination:
    server: https://kubernetes.default.svc
    namespace: tu-test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
  info:
    - name: Description
      value: Generic Application Deployment
    - name: Maintainer
      value: tu.nguyenx@homecredit.vn
