apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jsonnet-nginx
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/your-org/your-repo.git
    targetRevision: HEAD
    path: jsonnet-nginx
    directory:
      jsonnet:
        extVars:
          - name: environment
            value: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true 