apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
        - image: registry.vn.eit.zone/open-api/base-image/busybox:v1.3
          name: guestbook-ui
          command: ["sleep", "3600"]
